version: "3.1"

networks:
  proxy:
    external: true

services:
  backend:
    image: docker.io/eltonjhsouza/zapime-izing:2023-11-13-1
    volumes:
      - tokens:/app/tokens
      - images:/app/uploads
    command: npm run start
    networks:
      - proxy
    environment:
      - NODE_ENV=development
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=api-zapime.uaitizap.tech
        - com.df.port=3000
        - com.df.httpsOnly=false
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
      replicas: 1
      restart_policy:
        condition: any
volumes:
  tokens:
  images: