version: '3.1'
networks:
  proxy:
    external: true

services:
  izing-backend:
    image: docker.io/eltonjhsouza/zapime-izing:2023-11-17-1
    volumes:
      - tokens:/usr/src/app/.wwebjs_auth
      - public:/usr/src/app/public
    networks:
      - proxy
    environment:
      - NODE_ENV=development
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=api-zapime.uaitizap.tech
        - com.df.port=3000
        - com.df.httpsOnly=false
      resources:
        limits:
          memory: 1024M
          cpus: "2" 
      replicas: 1
      restart_policy:
        condition: any
volumes:
  tokens:
  public: